[package]
name = "network-stability-logger"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
crossterm = "0.21.0"
log = "0.4.14"
ping = "0.3.0"
simplelog = "0.10.2"
structopt = "0.3.23"
